### ISSUE TITLE
[Roadmap] Introduce plugin support for Ballerina Swan Lake

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/plugin-intellij#43]
**Description:**
We are planning to resume the IntelliJ plugin development effort, with the support for Ballerina Swan Lake versions. Please find the high-level roadmap of the proposed plugin below.

- [x] **Phase 1: Project Planning and Research**
  - [x] Project Proposal
  - [x] Technical Research

- [x] **Phase 2: Design and Architecture**
  - [x] System Architecture Document

- [x] **Phase 3: Development**
  - [x] Plugin Skeleton
  - [x] Parser and Lexer
  - [x] Integrate Language Server Protocol (LSP)
  - [x] Integrate Debug Adapter Protocol (DAP)

- [ ] **Phase 4: Testing**
  - [ ] Unit Testing
  - [ ] Integration Testing
  - [ ] User Acceptance Testing (UAT)

- [x] **Phase 5: Documentation**
  - [x] User Guide
  - [x] Developer Documentation

- [ ] **Phase 6: Deployment**
  - [ ] Beta Release
  - [ ] RC and Final Release
  - [ ] Post-Release Support

- More details on the roadmap can be found in [Ballerina Plugin Roadmap Document](https://docs.google.com/document/d/1MyX4UfoS__cljgMZNRofAz3hY2lMWVnDaQ-mu_dg9_A/edit?usp=sharing)

- The proposed overall architecture and design decisions can be found in our [Plugin Design Documentation](https://docs.google.com/document/d/1uEOeHqxEDkkTBFEhkmkL6KUF4DLrwvRY-oRkl3ESTWg/edit?usp=sharing)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
